### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Threshold' and 'PipeLine'

### ISSUE THREAD

**Issue by UriahShaulMandel** [GreenBlitz/GBVision#2]
I tried to run this [example](https://github.com/GreenBlitz/GBVision/blob/master/examples/find_nearest_cargo.py)
and got this error:

```
Traceback (most recent call last):
  File "C:/~~~~/GBVision.py", line 26, in <module>
    main()
  File "C:/~~~~/GBVision.py", line 13, in main
    find_cargo = gbv.CircleFinder(CARGO_THRESHOLD, CARGO)
  File "C:\~~~~\venv1\lib\site-packages\gbvision\finders\circle_finder.py", line 20, in __init__
    contours_to_circles_sorted +
TypeError: unsupported operand type(s) for +: 'Threshold' and 'PipeLine'
[ WARN:0] terminating async callback

Process finished with exit code 1
```

**Comment by idoheinemann** [comment]
We are aware of this problem and will fix it in the future
It happens because Threshold objects do not inherit from PipeLine
For now you can create a new PipeLine that wraps the threshold or add EMPTY_THRESHOLD + to the beggining of the sum

**Comment by UriahShaulMandel** [comment]
Ah ok, thanks!

**Comment by idoheinemann** [comment]
Fixed the bug
